--filter-l7=discord
    --payload=discord_ip_discovery
        --lua-desync=mangled:rnd=1--1:qty=1-2:starts_with=0x17fefd
        --lua-desync=send
        --lua-desync=mangled:rnd=1--1:qty=0-1:starts_with=0x17fefd
        --lua-desync=drop