--filter-l7=quic
    --hostlist-exclude={user-hostlist-exclude}
    --ipset-exclude={user-ipset-exclude}
    --ipset-exclude={ipset-exclude}
        --payload=quic_initial
            --lua-desync=luaexec:code=desync.qty=math.random(6,11)
            --lua-desync=fake:blob=quic_initial_www_google_com:repeats=%qty