--filter-l7=wireguard
    --ipset-exclude={user-ipset-exclude}
    --ipset-exclude={ipset-exclude}
        --payload=wireguard_initiation,wireguard_cookie
            --lua-desync=luaexec:code=desync.qty=math.random(11,16)
            --lua-desync=fake:blob=quic_initial_www_google_com:repeats=%qty